import os

COLOR_HIGH = "#ffcdd2"
COLOR_MEDIUM = "#fff9c4"
COLOR_LOW = "#e8f5e9"
COLOR_NONE = "#ffffff"
PRIORITY_COLORS = {
    "NOW": COLOR_HIGH,
    "SOONER": COLOR_MEDIUM,
    "ANYTIME": COLOR_LOW,
    "SOMEDAY": COLOR_NONE,
}
PRIMARY_COLOR = "#4CAF50"

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 800
TREE_WIDTH = 500
TREE_HEIGHT = 600
MAIN_WINDOW_WIDTH = 400
MAIN_WINDOW_HEIGHT = 500

TR_WIDTH_PRIORITY = 120
TR_WIDTH_NAME = 180
TR_WIDTH_DATE = 150

FONT_FAMILY = "Meiryo"

TIME_MS_SNOOZE = (
    10000 if os.getenv("TASK_MODE", "production") == "test" else 5 * 60 * 1000
)
TIME_MS_INTERVAL = (
    5000 if os.getenv("TASK_MODE", "production") == "test" else 30 * 60 * 1000
)
